### ISSUE TITLE
Re-add the ability to work offline

### ISSUE THREAD

**Issue by ericvsmith** [buildout/buildout#165]
buildout 1 supported the options --setup-source and --download-base. By setting these to a local resource, buildout would not use the network. A second use case is constrained environments, where a server might be able to talk to local http servers but not use the internet.

This feature request is to re-establish these options in buildout 2.

One open issue is whether to bring back --download-base as its own option, or to use the buildout 2 --find-links option. I favor re-using --find-links and not re-adding --download-base, but I could go either way. It seems like proliferating options, especially ones that are likely to have the same value, is not a good design.

**Comment by reinout** [comment]
This should be fixed with the latest bootstrap. From the 2.4.0 changelog:

The bootstrap script now accepts ``--to-dir``. Setuptools is installed
  there. If already available there, it is reused. This can be used to
  bootstrap buildout without internet access. Similarly, a local
  ``ez_setup.py`` is used when available instead of it being downloaded. You
  need setuptools 14.0 or higher for this functionality.
