### ISSUE TITLE
os.makedirs instead of os.mkdir?

### ISSUE THREAD

**Issue by guyzmo** [buildout/buildout#259]
Hi,

I'm using the following scheme for all my buildouts:

```ini
develop = .
develop-dir        = ${buildout:directory}/var/clone/
eggs-directory     = ${buildout:directory}/var/eggs
develop-eggs-directory = ${buildout:directory}/var/develop-eggs
parts-directory    = ${buildout:directory}/var/parts
```

the issue is that when I run `buildout`, it fails loudly (as expected) because `var` does not exists. So I have to add in all my repositories a `var/.placeholder` so my `buildout` always works fine. If I'm using such a scheme, it's because I find it tidier to have only two directories being changed by buildout instead of having `clone, eggs, develop-eggs, parts…` in the source's root. It's been a few years that I've been doing that, but I wondered why I couldn't ask for getting buildout to get along more nicely with my preference.

And actually python makes it quite easy to create a full path directory by switching to `os.makedirs`. So I had a look to the sources, was about to make a PR just for that when I saw that note in the sources, at commit 735aee2d:

```python
                    # Note: os.mkdir only creates the dir if the parent
                    # exists. This is the way we want it.
```

* So what is the rationale behind that? 
* Do _we_ really want it? I actually do not! ;-)
* Why would this be any better than `os.makedirs`, and what would it be protecting against?
* would you happily accept a PR switching `os.mkdir` to `os.makedirs`, and if so, would I have to protect the users' against any edge case I wouldn't think of?

**Comment by reinout** [comment]
I remember adding the "this is the way we want it" comment when I refactored that piece of code a bit. I don't remember why anymore, probably because there was a test for it somewhere. So... I replaced the `os.mkdir` with `os.makedirs` and ran all the tests.

All the tests run just fine. So I've got no hint why I added the comment in the first place.

The only reason I can think of is that buildout wants to prevent people from accidentally creating deeply nested directories in the wrong places. But... that's not really a problem, I think. Buildout prints out the directory name if it creates it.

Perhaps someone else knows the reason? Otherwise I'd say, make a pull request.

**Comment by mgedmin** [comment]
+1 for os.makedirs

**Comment by jimfulton** [comment]
I'm willing to defer, but I don't generally like the idea of creating multiple levels of directories.
It means that typos go unchecked.  I suppose that's less of an issue if the directories are rooted
in some known location, like the buildout directory, or are relative paths.

**Comment by guyzmo** [comment]
@jimfulton generally speaking I don't disagree, but given that the user is working properly and cleanly, he'll be working in a git environment and a simple `git checkout` will clean all the buildout mess in case he's doing wrong. Also, unlike with `mkdir -p`, per default it's going to yell if full path already exists, so then you cannot put everything in the same directory.

@reinout ok, I'll make a PR then!
