### ISSUE TITLE
Reuse requirements.txt for version pinning?

### ISSUE THREAD

**Issue by gforcada** [buildout/buildout#287]
I searched a little bit and found no direct question/issue about it, so...

Would it be a possibility to drop the `[versions]` section on our buildouts and reuse requirements.txt? With pip, wheels and the general python install ecosystem getting better and better, buildout has its own place of course, but maybe it's time to slim down and reuse other projects/files?

**Comment by do3cc** [comment]
I'd like that

**Comment by reinout** [comment]
Note that `requirements.txt` isn't the same as the `[versions]` part. Buildout could use it as a/the source of version pinning information, probably.

But pip doesn't only use it as a pin-list, but also as the list of packages to install (in addition to what's mentioned in the `setup.py`). This might lead to differences or bug reports due to differing expectations.

Any way to deal with this?

**Comment by do3cc** [comment]
Another issue:

Pip installs eggs in different locations and some packages rely on this. For example uwsgi.
I can pip install sentry, but I could not use a working requirements file to install sentry via buildout.
Sentry uses uwsgi and uwsgi does not find the eggs installed via buildout.

But then again, I'd probably use pip directly rather than buildout and delegate config file generation to buildout.

**Comment by leorochael** [comment]
Another issue is that `[versions]` contains a direct version specification for each egg, whereas requirements.txt can contain ranges of versions.

I believe a buildout extension should be able to use a `requirements.txt` with only `==` version specifications (i.e. like the one generated by `pip freeze`) to populate a virtual `[versions]` section.

Another possibility would be for a recipe that inherits from `zc.recipe.egg` to populate the `eggs` setting with the contents of a `requirements.txt` file.

In any case, I believe this could be tried in recipe or extension packages before being folded into buildout proper.

**Comment by do3cc** [comment]
+1 for extension package first.

**Comment by sirex** [comment]
[Another use case](https://github.com/buildout/buildout/issues/285#issuecomment-219646508). I use `buildout`, but do not use `zc.recipe.egg` for managing python packages, instead I manage all package with `pip + virtualenv`. `buildout` works quite well with `virtualenv`, but still all recipes are installed in a buildout's way so I have to keep both `versions.cfg` for pinning buildout recipe versions and `requirements.txt` for other packages.

Unfortunately `djangorecipe` depends on `Django` and pins version to `versions.cfg`, while `Django` is also listed in `requirements.txt`. If those pinned versions differ, then `buildout` overrides `requirements.txt`.

Now I have to update two files, `versions.cfg` and `requirements.txt`. It would be great if `buildout` could use `requirements.txt` instead of `versions.cfg`.

**Comment by enkidulan** [comment]
@sirex I guess you could make a good use of this two recipes: 

   1. https://pypi.python.org/pypi/gp.recipe.pip/0.5.3 - runs pip under buildout
   2. https://pypi.python.org/pypi/collective.recipe.pip/0.3.2 - extends buildout versions from pip requirements files 

I would say that trying mixing pip with zc.builout isn't the good approach in most cases.

**Comment by sirex** [comment]
> https://pypi.python.org/pypi/gp.recipe.pip/0.5.3 - runs pip under buildout

Usually I install `zc.buildout` in an already created virtualenv (see: https://github.com/buildout/buildout/issues/289), together with all other project packages, so there is no point of using `gp.recipe.pip`.

>  https://pypi.python.org/pypi/collective.recipe.pip/0.3.2 - extends buildout versions from pip requirements files 

Thanks. Interesting. But it looks that `collective.recipe.pip` can only read `requirements.txt` but does not support writing to it. It means, that I can benefit from it, by reading pinned versions, but still I will have to store pinned versions of recipe packages installed by buildout in `versions.cfg`.

> I would say that trying mixing pip with zc.buildout isn't the good approach in most cases.

Why?

Second statement from [buildout's readme](https://github.com/buildout/buildout/blob/921fd34a17d7165bafb5e3ea5c1676a4f87f6d21/README.rst#installation) says „_You can install it as you would any other package, using pip or easy_install._“ As I understand, installing buildout using pip install virtualenv is recommended way of installing buildout.

Also, buildout changelog says: „_Buildout no-longer tries to provide full or partial isolation from system Python installations. If you want isolation, use buildout with virtualenv, or use a clean build of Python to begin with._“ it means, that everything installed inside virtualenv is visible to buildout.

**Comment by enkidulan** [comment]
@sirex, sorry for confusion, I was saying it in context of managing packages and dependencies inside project. Venv is great tool for isolation and pip is "an easy" way to install anything, I'm using them to have buildout tool installed in clean python env. Issue #285 seems to be about installing buildout itself and not about projects assembling or versions control inside projects.

The point is that in charge of version control inside the project should be only one tool, otherwise it may become an assembling and version control hell. Having part of dependencies installed and controlled by buildout and another part by pip would lead to number of possible issues with versions overrides, mismatches, missing packages and need to support the couple of the same version registers and running a couple of different tools that do kind of the same at some point to assemble the project. zc.buildout apart from other it's features is a way much more convenient in controlling versions then pip, especially with using different `allow-picked-versions`, `newest` and `show-picked-versions` options for different types of builds. 

The benefit from using `gp.recipe.pip` is that it makes buildout in charge of version control so there won't be any need to have requirements.txt at all. With that recipe it's even possible to use different pythons for different parts of projects and still have plain, easy to support and strict dependencies control, except the cases when you need to have different versions of same package. That works for me very well.

**Comment by sirex** [comment]
@enkidulan thanks for explanation, and I agree that it is better to have one tool for managing packages, and I prefer to trust this task to `pip`. For pinning versions I use [pip-tools](https://github.com/nvie/pip-tools).

Quite recently I switch one project from `zc.recipe.egg` to `pip + pip-tools` and found that it works quite well, except for recipes, recipes are still installed using `buildout`. I guess adding possibility to completely turn off package management in buildout would require quite big refactoring, but adding support for requirements.txt would be easier thing to do.

**Comment by enkidulan** [comment]
@sirex , I guess that behaviour can be achieved by combining recipes:
  * `gp.recipe.pip` will make buildout in charge for version control and assembling with using pip for packages installation
  * `pip freeze` or `pip-compile` command will generate `requirements.txt` 
  * `collective.recipe.pip` will allow buildout to use that `requirements.txt` files generated from earlier 

On second thought the format that pip uses for its requirements files is very poor, the main issue I have with it is that it doesn't support having different types of dependencies, I mean something like  `extras_require` in setup.py. What I would vote for is making `requirements.txt` compatible with buildout, but not vice versa :)

**Comment by jimfulton** [comment]
I like seeing this discussion happening.

My view is (still) that:

- There should be a recipe or recipes that create Python scripts based on pip+virtualenv. As this matures, this should become the recommended way to assemble Python applications with buildout. (Not because I like pip, but because it has won the packaging discussions and I don't want to try to beat it.)

- Buildout should work the way it does now for the foreseeable future both for handling recipes and for backward compatibility (and because doing so requires the least effort).  Eventually, at least in living projects, buildut will use setuptools only for recipes.

**Comment by gforcada** [comment]
Seems that we are slowly transitioning to this, but adding other tools (`mxdev` and maybe others?) to the mix 🎉
