### ISSUE TITLE
Parallel buildout runs can break a new egg

### ISSUE THREAD

**Issue by mauritsvanrees** [buildout/buildout#307]
When you run two buildouts next to each other and they both install the same distribution that you did not have before, then this can lead to a broken egg.
This assumes eggs as directories and not as zipped files, but that is the default.
What happens, is this:

- Both buildouts create the egg in their own temporary directory.
- The first buildout starts moving the files of the egg to the `eggs/package.egg` directory.
- The second buildout is slightly later, sees that `eggs/package.egg` already exists, and starts to remove it.
- The first buildout was not quite finished moving all the files, so it keeps doing that.
- The second buildout has removed all the files that it saw and tries to remove the directory, but this fails with an `OSError` because the directory is no longer empty. It does not do anything fancy here, it simply fails while calling `shutil.rmtree`.
- The first buildout may or may not continue, but it will leave behind an egg directory with only a part of the files.
- Subsequent buildout runs see that the egg is there, so they happily continue. But anything that tries to use the egg, will run into problems like `ImportErrors` or other missing files.

I see this happen too often on the Continuous Integration server of Plone: http://jenkins.plone.org. We have four nodes (machines). Each node has three jobs or executors. Each job runs a buildout. All jobs on a node share the same egg cache to prevent using three times as much disk space.
When I make a change in Plone to use a new package, multiple buildouts are started and they may end up on the same node. Most of the time this goes fine. But too often we run into the situation I describe above.

A sample traceback you get is this, which is what happens in the second buildout:

```
While:
  Installing robot.
  Getting distribution for 'Products.CMFEditions==2.2.21'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/jenkins/.buildout/eggs/zc.buildout-2.5.2-py2.7.egg/zc/buildout/buildout.py", line 1995, in main
    getattr(buildout, command)(args)
  File "/home/jenkins/.buildout/eggs/zc.buildout-2.5.2-py2.7.egg/zc/buildout/buildout.py", line 666, in install
    installed_files = self[part]._call(recipe.install)
  File "/home/jenkins/.buildout/eggs/zc.buildout-2.5.2-py2.7.egg/zc/buildout/buildout.py", line 1410, in _call
    return f()
  File "/home/jenkins/.buildout/eggs/zc.recipe.egg-2.0.3-py2.7.egg/zc/recipe/egg/egg.py", line 126, in install
    reqs, ws = self.working_set()
  File "/home/jenkins/.buildout/eggs/zc.recipe.egg-2.0.3-py2.7.egg/zc/recipe/egg/egg.py", line 84, in working_set
    allow_hosts=self.allow_hosts)
  File "/home/jenkins/.buildout/eggs/zc.buildout-2.5.2-py2.7.egg/zc/buildout/easy_install.py", line 883, in install
    return installer.install(specs, working_set)
  File "/home/jenkins/.buildout/eggs/zc.buildout-2.5.2-py2.7.egg/zc/buildout/easy_install.py", line 664, in install
    for_buildout_run=for_buildout_run):
  File "/home/jenkins/.buildout/eggs/plone.versioncheck-1.3-py2.7.egg/plone/versioncheck/tracking.py", line 22, in get_dist
    dists = old_get_dist(self, requirement, *ags, **kw)
  File "/home/jenkins/.buildout/eggs/zc.buildout-2.5.2-py2.7.egg/zc/buildout/easy_install.py", line 552, in _get_dist
    dist.location, ws, self._dest, dist)
  File "/home/jenkins/.buildout/eggs/zc.buildout-2.5.2-py2.7.egg/zc/buildout/easy_install.py", line 403, in _call_easy_install
    shutil.rmtree(newloc)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 254, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty:
'/home/jenkins/.buildout/eggs/Products.CMFEditions-2.2.21-py2.7.egg/Products/CMFEditions'
```

See for example http://jenkins.plone.org/job/plone-5.1-python-2.7-robot/707/console

In the first buildout it may lead to this traceback:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/py_compile.py", line 181, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/py_compile.py", line 173, in main
    compile(filename, doraise=True)
  File "/usr/lib/python2.7/py_compile.py", line 106, in compile
    with open(file, 'U') as f:
IOError: [Errno 2] No such file or directory:
'/home/jenkins/.buildout/eggs/Products.CMFEditions-2.2.21-py2.7.egg/
Products/CMFEditions/UniqueIdHandlerTool.py'
While:
  Installing robot.
  Getting distribution for 'Products.CMFEditions==2.2.21'.
```

See for example http://jenkins.plone.org/job/plone-5.1-python-2.7/693/console

Result: someone has to login to the node with ssh, [remove the broken egg](https://github.com/plone/jenkins.plone.org/issues/188), and restart a job. And it leads to me proposing [crazy workarounds](https://github.com/plone/jenkins.plone.org/pull/166) for our Jenkins server to avoid running multiple buildouts at the same time. I would rather fix it in zc.buildout.

The first traceback points to a place where we may be able to fix this. The `shutil.rmtree` call fails. I propose that we catch this error, wait five seconds, then try it again. If it still fails, we crash.

I will make a pull request, but wanted to write down the problem first.

**Comment by leorochael** [comment]
Hi @mauritsvanrees, thanks for looking into this.

We already discussed parts of this on the pull requests, but I spent so long writing it that I don't want to throw it away :wink:.

In essence the issue is that buildout is having a race condition while doing non-atomic operations on a shared resource.

From the tracebacks you posted, it doesn't look like the problem happens when the first buildout is copying the files in place because that is done atomically inside `_call_easy_install()` in the line that says:

 * `os.rename(d.location, newloc)`

Rather, it looks like it happens when the first buildout is calling [`py_compile`](https://docs.python.org/2/library/py_compile.html) (called by `redo_pyc()`) after the files have already been moved in place.

There is a non-atomic copy operation that can happen, though: when the source package is an egg directory, the `_get_dist()` function calls `shutil.copytree()` directly to the destination. It should instead create a `tempdir()` inside the egg cache, call `shutil.copytree()` there and then move the result back into the egg cache. Otherwise another buildout could attempt to use the egg before the copy is finished, and cause very intermittent errors.

In any case, not only are `py_compile`, `copytree()` and `rmtree()` non-atomic operations being executed on a shared resource, but the sequence of trying to remove the target directory and then moving another directory to the target is non-atomic, even if we can make each part atomic.

I think retrying once one-shot idempotent operations in case of a race condition in a shared resource is a strategy that can work, but only if you're retrying the whole operation, which in this case is the attempt to install a package.

If buildout tried again the whole package install after failure, the second time around it would see the package already exists and would do nothing.

However since `rmtree()` is non atomic, I suspect that retrying it would just make the error less likely, not eliminate it. To make the removal atomic, buildout should create a `tempdir()` inside the egg cache, move the directory there and `rmtree()` the whole thing.

Even then, I fear making the removal atomic is not enough. Taking your reported sequence as an example:

 * Both buildouts create the egg, each in their own temporary directory in the egg cache.
 * The first buildout starts building (or copying) in the `eggs/TeMpOrArY` directory (which should be created with `tempfile.mkdtemp(..., dir="eggs")`. When it's done it will move it to `eggs/package.egg`.
 * The second buildout will either see the directory in it's final name or it won't:
  * If it's early, it won't see the `eggs/package.egg` directory and will also start it's own copying (or building) in another temporary directory inside the `eggs/`, but will fail atomically while trying to rename to the final name. This error could perhaps be ignored since the end result is the same.

  * If it is slightly late it will see that `eggs/package.egg` already exists, move it out atomically to remove it and then replace it with its own copy. But this could still cause an error on the other buildout trying to call `py_compile` on it.

So, all in all, just making `copytree()` and `rmtree()` atomic by following/preceding them with a `os.rename()` into a `tempdir()` would at least stop the runs from leaving broken eggs behind, but would cause intermittent failures.

I believe the correct solution would be to make all install/copy operations atomic **and also** stop trying to remove the target directory before installing it again. If an install operation fails on the last rename, check the destination already exists (and perhaps check that it is a proper egg) and continue without an error.

Unfortunately the `py_compile`/`redo_pyc` step cannot be made atomic, as it would require doing it before the `os.rename()`, which would report wrong paths inside the `.pyc` files in tracebacks (we've been through this before with buildout already). But I think two buildouts running `py_compile` on the same directory shouldn't be too much of an issue.

Would be nice if we could avoid it, though. E.g. by only calling `redo_pyc` on directories where the `os.rename()` was successful.

**Comment by mauritsvanrees** [comment]
Sounds correct. Thanks for thinking about this and writing it down.

I have updated #310 in a way that I think implements the correct solution that you describe above, including the compile step.

**Comment by mauritsvanrees** [comment]
Note that previously, first all dists were gathered, then they were compiled, if I see it correctly. With my implementation, after a single dist is fetched and put in the destination directory, it gets compiled, and then the next dist is fetched.  So the order of execution slightly changes, though this actually seems better to me.

In the pull request I have updated the version number of zc.buildout to 2.6.0, as these seem like too big changes for a micro release.  Subtle things may go subtly wrong with this, if only because the output of a buildout run may have a different order, which can influence doctests of buildout recipes.
