### ISSUE TITLE
Provide a way for a part to declare that it depends on other parts without using value interpolation.

### ISSUE THREAD

**Issue by jimfulton** [buildout/buildout#366]
See: https://groups.google.com/forum/#!topic/buildout-development/NIm9kDrnmE8

We didn't reach a conclusion there. In the mean time, I'm going to rework the implicit parts example, https://github.com/buildout/buildout/blob/implicit-parts/doc/topics/implicit-parts.rst to use the server example and just note this issue.

**Comment by mauritsvanrees** [comment]
That would be useful. We ran into this problem with [`collective.solr`](https://github.com/collective/collective.recipe.solrinstance/issues/58).
Basic example would be a buildout config like this:

```
[solr-instance]
recipe = collective.recipe.solrinstance:mc
cores = core1

[core1]
option-for-this-core = foo
```

A change in `core1` should result in rebuilding the `solr-instance` but this is not happening, because there is no way yet in buildout to specify that.
The workaround for this recipe was that we added code to include all the options of the dependencies in the options of the recipe, so they would be stored in `.installed.cfg`. See [here](https://github.com/collective/collective.recipe.solrinstance/pull/61/files#diff-e9704fdb9716ae57883502dd0b393d72R210).
