### ISSUE TITLE
Couldn't find index page for 'mr.developer'

### ISSUE THREAD

**Issue by jimmyzhen** [buildout/buildout#420]
Running `buildout` failed due to following error:
```
Couldn't find index page for 'mr.developer' (maybe misspelled?)
Getting distribution for 'mr.developer==1.31'.
Couldn't find index page for 'mr.developer' (maybe misspelled?)
While:
  Installing.
  Loading extensions.
  Getting distribution for 'mr.developer==1.31'.
Error: Couldn't find a distribution for 'mr.developer==1.31'.
```
Please give me pointers on how this can be resolved. Thank you!

**Comment by jamadden** [comment]
Do you perhaps have a custom index URL specified for PyPI? Or are you using a version of zc.buildout older than 2.9.5? If so, you will probably need to manually specify the URL to [be HTTPS instead of HTTP](https://github.com/buildout/buildout/issues/114). PyPI recently [disabled all API support for HTTP](https://mail.python.org/pipermail/distutils-sig/2017-October/031712.html).

**Comment by jimmyzhen** [comment]
Hi @jamadden,

Thank you very much for the pointers!

We are indeed using `zc.buildout` _2.3.1_ which appears to have the following in its `easy_install.py`:
```
default_index_url = os.environ.get(
    'buildout-testing-index-url',
    'http://pypi.python.org/simple',
    )
```
I don't believe we have a custom index URL specified for PyPI. But just in case we do, where do we usually look for its configuration? In the `buildout.cfg`, and/or other places?

And if we are to update our `zc.buildout` from _2.3.1_ to _2.9.5_, will there be any ramifications that we shall be aware of?

**Comment by jamadden** [comment]
I believe you're looking for the [`index` configuration setting](http://docs.buildout.org/en/latest/reference.html#buildout-configuration-options), which, if present, is usually in your buildout configuration file (or one it extends), but I think it can also be set on the command line.

As for upgrading from 2.3.1 to the latest, all I can suggest is that you review the [change notes](https://pypi.python.org/pypi/zc.buildout#id22) for the intervening versions. 2.3.1 is pretty old, so there is a lot to review...(that said, my group has been using buildout since roughly 2.0, upgrading frequently, and I don't recall any major issue along the way that weren't solved in a subsequent release).

**Comment by jimmyzhen** [comment]
Hi @jamadden,

I have confirmed that there isn't a custom index URL in our buildout config file.

Prior to running the buildout, we also run the following:
```
python bootstrap.py -v 2.3.1 --setuptools-version 15.2
```
I assume that we also need to change `bootstrap.py` to 2.9.5 as a result of the upgrade. Any ideas on whether the older version of `setuptools-version` would be an issue?

**Comment by jamadden** [comment]
That's an ancient version of setuptools (current is 36.x). I'm sure that current buildout is not tested against it, and I also know that buildout assumes certain information about how setuptools works, so I have no idea what would happen if you mixed the two.

I'm afraid this is straying from the topic of this issue and my ability to assist. I hope that either upgrading buildout or setting an index URL works for you!

**Comment by jimmyzhen** [comment]
Hi @jamadden,

Thank you for the advice on the `setuptools`. We will look into upgrading it as well.

Meanwhile, upgrading `zc.buildout` to _2.9.5_ appears to have allowed me to run the buildout locally without the issue we've been discussing. The next thing will be for us to test the upgrade with our CI and cloud services.

You have been tremendously helpful! 💯 THANK YOU!

**Comment by jamadden** [comment]
Awesome, I'm glad you found something that works! If this is solved, con you close this issue?

**Comment by jimmyzhen** [comment]
Sure thing!
