### ISSUE TITLE
Document meaning of "Unused options for.."

### ISSUE THREAD

**Issue by jugmac00** [buildout/buildout#483]
I encountered above message when trying to run buildout on the current head of Zope https://github.com/zopefoundation/Zope/commit/c9871f5fc2cefacf1839e09934eb0c5fadc9a2da

Searching for "unused" in the buildout documentation brought up zero hits.
http://www.buildout.org/en/latest/search.html?q=unused&check_keywords=yes&area=default

Complete message:

```
Installing requirements.
requirements: Running '/home/jugmac00/Tests/Zope/bin/zopepy util.py'
Unused options for requirements: 'update-command'.
```

The problematic line would be the one starting with update-command:
https://github.com/zopefoundation/Zope/blob/c9871f5fc2cefacf1839e09934eb0c5fadc9a2da/buildout.cfg#L172-L177

**Comment by leorochael** [comment]
In Buildout, the options of a `part` (a configuration section with a recipe, in this case the `[requirements]` part with a `plone.recipe.command` part) are made available in a dictionary-like object that tracks which keys are actually used.

If a key is not used by the recipe of a `part`, then buildout warns about it. As a warning, it is not supposed to cause the buildout run to fail.

The main use of this behavior is making sure you didn't misspell a settings value. In this specific case, it's warning that `plone.recipe.command` did not make use of the `update-command` key in the configuration on that specific buildout run.

Perhaps Buildout documentation (and maybe the error message) should be improved to make this behavior easier to understand, but I don't consider this a bug in Buildout.

If anything, since `update-command` is a [documented setting](https://pypi.org/project/plone.recipe.command/) of `plone.recipe.command`, I consider it a bug on that recipe that it doesn't touch the `update-command` key in the settings dictionary when it doesn't need it, causing this warning to appear.

**Comment by jugmac00** [comment]
@leorochael, thank you very much for this super detailed answer.

I think it would be a great idea to both extend the warning message and add a paragraph to the documenation, maybe here:
http://www.buildout.org/en/latest/getting-started.html

I try to find some time next week and create a pr.

**Comment by leorochael** [comment]
Another comment regarding unused options: it's possible for a part to define an option not for it's own consuption, but for consumption by other parts, which will cause a dependency between those parts an the part that defines the option.

This is particularly useful if the option is defined in terms of other values (especially implicit default values) of a part.

If the part itself doesn't use an option, but another part does, the the warning is not shown (I think).

**Comment by jugmac00** [comment]
@leorochael Thanks for the update!

It is October ( Hacktober :-) ), but I think it is better to wait until #487 is fixed before I start working on this pr. Good luck to @mgedmin, @icemac and @reinout - seems to be a really tough one!

**Comment by gotcha** [comment]
@jugmac00 Would you make a PR now that #487 is closed 😉 ?

Or should we close this issue ?

**Comment by jugmac00** [comment]
Thanks, @gotcha, I assigned myself for this issue.

I have a huge open source backlog, but I will def. go for it.

Thanks so much for fixing CI and for all the work in general you put into `buildout`.
