### ISSUE TITLE
How to diagnose 'eggs' versions conflicts and to freeze dependencies

### ISSUE THREAD

**Issue by luffah** [buildout/buildout#532]
Hello, 

  using buildout for many projects and i often encounter issues when :
  - adding a package
  - using a buildout config file (to install in production environment) some months after the original setup
 
  In both case, it appears when dependencies of zc.recipes conflicts with additional packages. 

  Is there some option to get a freeze , dry-run, or anything that could help to detect (and fix) where are the conflicts ?

**Comment by mauritsvanrees** [comment]
The basis is knowing what packages you have that are 'picked', in other words: packages for which there is no version pin in the buildout config, but Buildout picks a version, usually the latest.
To know this, I have this in most buildout configs:

```
[buildout]
allow-picked-versions = false
show-picked-versions = true
```

With `allow-picked-versions = false` you disallow Buildout to pick a version. If Buildout sees it needs to install a package and there is no version pin, then it quits with an error, something like "Error: picked version foo = 1.0.0." Next step is to add `foo = 1.0.0` to your `[versions]` section (if you agree this version is fine) and run Buildout again.  Repeat until there are no errors. 

If you have dozens of picked versions that you fix this way, then you will likely fall asleep, so instead you can temporarily set `allow-picked-versions = true` and then have `show-picked-versions = true`. This will print a list of packages with picked versions at the end of the Buildout run. Copy those to the versions section, set `allow-picked-versions = false` again, and you should be good to go.

If you have a development buildout config and a production config, you need to make sure any extra production packages are pinned as well. And maybe you are running Buildout on Linux, and Windows or Mac need a few more pins, otherwise Buildout will fail there with picked versions.

But with that, you should get the exact same versions when you run this Buildout again a few months later, or on a different machine.

For version conflicts: I think somewhere around `zc.buildout` 2.9.x Buildout got more verbose at describing a version conflict, giving you all the minimum and maximum requirements for a conflicted package. That should give you enough information to hopefully solve the conflict.
Recent `pip` versions have an improved version conflict resolution, though I think it is not enabled by default but with an option. So if you can't see how to solve a conflict in Buildout, then maybe you can first try to install all packages with pip and see what versions it comes up with.

**Comment by luffah** [comment]
fine :)
